### ISSUE TITLE
500 - Internal Server Error

### ISSUE THREAD

**Issue by JoKalliauer** [toollabs/convert#2]
I tried to convert [Beamforming.pdf](https://github.com/toollabs/convert/files/3051412/Beamforming.pdf) to svg as requested by
[:de:Wikipedia:Grafikwerkstatt](https://de.wikipedia.org/wiki/Wikipedia:Grafikwerkstatt#Vorschlag_f%C3%BCr_neue_Abb._zum_Artikel_Beamforming)

But https://tools.wmflabs.org/convert/ redirects me to https://tools.wmflabs.org/convert/pdf2svg.php with the message `500 - Internal Server Error`.

<details>

<summary>Copyright, Source</summary>

Author: [Acky69](https://de.wikipedia.org/wiki/Benutzer:Acky69)

License:
{{[Bild-CC-by-sa/3.0/de](https://creativecommons.org/licenses/by-sa/3.0/de/legalcode)}}
{{Bild-CC-by-sa/3.0}}
{{Bild-GFDL-Neu}}

Source: https://de.wikipedia.org/wiki/Datei:Beamforming.pdf

</details>

**Comment by Rillke** [comment]
After seeing the following in the logs, I guess this was an operational issue of the tool forge platform:

```
2019-04-07 17:10:00: (chunk.c.553) opening temp-file failed: No such file or directory 
2019-04-07 17:10:16: (chunk.c.553) opening temp-file failed: No such file or directory 
```

Please confirm, and close this issue, or report at Phabricator. Thanks for your report.

**Comment by JoKalliauer** [comment]
Thanks for your answer!

It seems to work now, therefore closing this issue.
